# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Seth Comire's Blog
tagline:             ''
description:         'A repository for me to track everything I have learned (since starting this page).'
url:                 https://semico6.github.io/blog/
baseurl:             '/blog'
paginate:            5

# About/contact
author:
  name:              Seth Comire
  url:               https://twitter.com/nemophilist345
  email:             nemophilist345@protonmail.com

# Custom vars
version:             1.0.0
